kind: ConfigMap
apiVersion: v1
metadata:
  name: rhel7-test-vm-az-a-config
  namespace: post-upgrade-testing
  labels:
    environment: ansible-test-rhel7-test-vm-az-a
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World</title>
    </head>
    <body>
        <p>Hello World</p>
    </body>
    </html>