apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhel7-test-vm-az-a-pvc1
  namespace: post-upgrade-testing
  labels:
    environment: ansible-test-rhel7-test-vm-az-a
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: az-a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhel7-test-vm-az-a-pvc2
  namespace: post-upgrade-testing
  labels:
    environment: ansible-test-rhel7-test-vm-az-a
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: az-a