apiVersion: v1
kind: Secret
metadata:
  name: rhel7-test-vm-az-a-ssh-key
  namespace: post-upgrade-testing
  labels:
    environment: ansible-test-rhel7-test-vm-az-a
type: Opaque
data:
    authorized_keys: ENCODED_AUTO_GENERATED_AUTHORIZED_KEYS_CONTENT