---

  - name: Retrieve content of the local ssh public key
    ansible.builtin.set_fact:
      ssh_key: "{{ lookup('file', SSH_PUBLIC_KEY ) }}"

  - name: Render the 'pub_key_secret.j2' template to generate Secret definition
    ansible.builtin.template: 
      src: "pub_key_secret.j2" 
      dest: "files/pub_key_secret.yml"

  - name: Deploy the generated Secret yaml
    k8s:
      state: present
      src: "files/pub_key_secret.yml"
    register: pub_key_secret_info